---
- name: file creation
  hosts: all
  tasks:
  - name: test file creation
    file: 
      path: "/opt/Hello-Cloudgen"
      state: present

      # it didn't work as the state : PRESENT is not taken by the system
      